version: '3.9'

services:
  mysql_db:
    image: mysql:5.7
    container_name: db
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file: ./db/.env
    restart: always
    volumes:       
      - db:/var/lib/mysql
      - ../migrations/init:/docker-entrypoint-initdb.d
    networks:
      - reldens
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -P 3306 -ppassw0rd | grep 'mysqld is alive' || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 10
        
  app:
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    container_name: app
    env_file: ./app/.env
    restart: unless-stopped
    networks:
      - reldens
    depends_on:
      mysql_db:
        condition: service_healthy
    ports:
      - 8080:8080
    expose:
      - 8080

networks:
  reldens:

volumes:
  db:
    driver: local
